name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint semantics --exit-zero | tee pylint.txt
    - name: Verifying minimum pylint score
      run: |
        python -c "print(open('pylint.txt').read().split('rated at ')[-1].split('/')[0])"|tee pylint_score.txt
        python -c "score=float(open('pylint_score.txt').read());assert score>=9.5,'Failing score: %s'%score"
